// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xifhyvqwfqyfdhfasgtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZmh5dnF3ZnF5ZmRoZmFzZ3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjQ3ODQsImV4cCI6MjA2NzI0MDc4NH0.Dndvbazqk9fd7wbLj0GohtiUb8ZecVs7KqEKv8pnInM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});